package Dto;

public enum ActionName {
	UPLOADIMAGE, ALLCATEGORY, ADDCATEGORY, REMOVECATEGORY, UPDATECATEGORY, GETCATEGORYCODENAME, ALLNEWS, REMOVENEWS,
	ADDNEWS, UPDATENEWS, SEARCHNEWS, SEARCHCATEGORY, REPORTCATEGORY
}
